theming
tbolwerk/ChatApp pull request #45
Opened 2021-12-11 10:25 UTC by tbolwerk

2021-12-11 17:30 UTC, stefthijssen reviewed
Check even of die tts wel degelijk uit de api moest gehaald worden.

2021-12-11 17:30 UTC, stefthijssen commented on Project/feature-u-soundboard-api/src/index.ts
> -});
Waarom haal je dit weg?

2021-12-11 17:34 UTC, stefthijssen requested changes
De knop werkt, maar hij verandert niet echt het theme van de gehele website. e.g.
![image](https://user-images.githubusercontent.com/33953289/145686088-eb60a7e4-79cc-4f92-bd5b-519aa4afa835.png)

2021-12-12 09:54 UTC, tbolwerk commented on Project/feature-u-soundboard-api/src/index.ts
> -});
omdat dit niet bestaat createTTS

2021-12-12 10:24 UTC, tbolwerk commented
> De knop werkt, maar hij verandert niet echt het theme van de gehele website. e.g. ![image](https://user-images.githubusercontent.com/33953289/145686088-eb60a7e4-79cc-4f92-bd5b-519aa4afa835.png)

fixed

2021-12-12 12:57 UTC, stefthijssen approved these changes

2021-12-12 12:58 UTC, merged